### ISSUE TITLE
Angular 2 Tour Of Heroes Tutorial - templateUrl does not resolve.

### ISSUE THREAD

**Issue by Bucabug** [angular/angular.io#2480]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

In the section "Dashboard Top Heroes" it states to set the templateUrl on app/dashboard.component.ts to: 'dashboard.component.html'

As follows:

````typescript
@Component({
    selector: 'my-dashboard',
    templateUrl: 'dashboard.component.html',
})
export class DashboardComponent {...)
````

This results in a 404 when trying to retrieve dashboard.component.html

![image](https://cloud.githubusercontent.com/assets/10373596/18842440/ed6f8040-840c-11e6-840d-9805df0bbad7.png)

**Expected behavior**

It seems like you need to qualify the path to the templateUrl.

The following code works without issue:

````typescript
@Component({
    selector: 'my-dashboard',
    templateUrl: 'app/dashboard.component.html',
})
export class DashboardComponent {...)
````
![image](https://cloud.githubusercontent.com/assets/10373596/18842642/9ef7932a-840d-11e6-9c21-86790840f59c.png)

**Please tell us about your environment:**

* **Versions**  

package.json:

````javascript
{
  "name": "tour-of-heroes",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.23",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings":"^1.3.2"
  }
}
````

**Comment by Bucabug** [comment]
Also hit the same issue in the "Find our way back" section on the same page. This time for the "hero-detail.component.html"

**Comment by Bucabug** [comment]
It looks like for the relative path to work the Components need a moduleId setting.

http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/

It seems like the options are to update the guide to include a moduleId or update the guide to include a full path.

Being new to Angular I don't know which of these options would be considered best practice however.

**Comment by vicen007** [comment]
I too was having this problem. In order for me to finish the tutorial, I had to keep the css and html within my TS files.

**Comment by Kilo59** [comment]
Having the same issue with both the dashboard and hero-details pages but changing the templateUrl to 'app/dashboard.component.html' doesn't fix it for me. 

After inspecting the "sources" it seems like html files are just being ignored inside of the app folder.

![toh_bug1](https://cloud.githubusercontent.com/assets/13108583/19002855/08ff9068-871c-11e6-9c78-6280ef542cb7.PNG)

**Comment by timxzz** [comment]
After changed the url path, should also add `moduleId: module.id,` in the `@Component` section, this issue is fixed in merge request #2477

**Comment by Foxandxss** [comment]
You need to use module.id indeed.

I am going to update the tutorial so it gets clear that you have to use it and how.

**Comment by asantiago323** [comment]
@SamFarrington I do not know if the tutorial was edited after the bug was written, but it seems like you forgot to place a "./" before your template location, hence why using "app/" worked for you. The "./" tells the app to search within the same folder for the document.

`@Component({
    moduleId: module.id,
    selector: 'my-dashboard',
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.css']
})`

**Comment by Sir4ur0n** [comment]
@asantiago323 Even with "./" this doesn't work, I just tested.

Speaking of which, I am surprised this ticket is closed. Today https://angular.io/docs/ts/latest/tutorial/toh-pt5.html still doesn't mention this `moduleId: module.id,` as far as I can tell, and the problem persists.

**Comment by Foxandxss** [comment]
We made a change recently to eliminate the `moduleId` need. We added a loader that will translate `./urls` into `absolute/urls/links.html`

**Comment by Sir4ur0n** [comment]
Then shouldn't the tutorial work? :( It doesn't right now, or I missed some important piece. It seems to work with `moduleId` though.

**Comment by Foxandxss** [comment]
Yes, of course. Show me your error and the code so we can debug it together.

**Comment by Sir4ur0n** [comment]
All problems happen using https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

1) The "live example" doesn't work. It gets stuck on "Loading...":
![image](https://cloud.githubusercontent.com/assets/1204125/24081936/971c77d6-0cbd-11e7-8d63-2c30186e0830.png)


2) With the downloadable example, after `npm install` (no error) and `npm start` I get `GET http://localhost:3000/systemjs-angular-loader.js 404 (Not Found)`. In the npm logs I see this: `[1] 17.03.19 16:58:39 404 GET /systemjs-angular-loader.js`.

3) When following manual steps of tutorial, on step 5, at `Dashboard Top Heroes` section (the very first time `templateUrl` is mentioned), the extraction of the template into `dashboard.component.html` doesn't work, I get this error: `GET http://localhost:3002/dashboard.component.html 404 (Not Found)`

```typescript
// app/dashboard.component.ts
import {Component, OnInit} from "@angular/core";
import {Hero} from "./hero";
import {HeroService} from "./hero.service";

@Component({
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent implements OnInit {

  heroes: Hero[];

  constructor(private heroService: HeroService) {
  }

  ngOnInit(): void {
    this.heroService.getHeroes()
    .then(heroes => this.heroes = heroes.slice(1, 5));
  }
}

// app/dashboard.component.html
<h3>Top Heroes</h3>
<div class="grid grid-pad">
  <div *ngFor="let hero of heroes" class="col-1-4">
    <div class="module hero">
      <h4>{{hero.name}}</h4>
    </div>
  </div>
</div>
```

**Comment by Foxandxss** [comment]
Ohh, yes, someone saw that loader problem. Something happened, I need to check that, that shouldn't be broken.

Sorry about that.

**Comment by jurban1997** [comment]
The tutorial is incorrect on the Component references to URL values.  The styleUrls and templateUrl need to be preceded by "../app/"  as in '../app/dashboard.component.html'.  I'm developing on Windows, so this may be the issue if non-windows environments are not experiencing this issue.

**Comment by Foxandxss** [comment]
I am not experiencing anything on windows

**Comment by asantiago323** [comment]
The "./" will work if they are contained in the same folder. It is working on my side without issues.
My code can be found here: https://github.com/asantiago323/heroes-app.
Now, this is just a random question, have you added the DashboardComponent to the ngModule/declarations section in the app.module.ts file? I usually get errors and stuff failing to load if I forget to import it everywhere it is being/supposed to be called.

**Comment by Sir4ur0n** [comment]
@asantiago323 It works because you have `moduleId: module.id,` in dashboard.component.ts. This is nowhere in https://angular.io/docs/ts/latest/tutorial/toh-pt5.html. Remove this line and it will break :)

**Comment by asantiago323** [comment]
I commented it out and it loaded.
<img width="777" alt="screen shot 2017-03-20 at 7 13 43 pm" src="https://cloud.githubusercontent.com/assets/19176941/24127291/71532f2e-0da1-11e7-9bae-baa5cb7f20d1.png">

**Comment by asantiago323** [comment]
I would have to look at what you guys have to troubleshoot what is going wrong. If someone can host their code and link it here, then we can poke it with a stick and find the source of the problem. Another thing that causes me headaches is fat-fingering something, like a semi-colon vs a colon or coma/period...

**Comment by ecarrera** [comment]
Could it be a bug of Angular or System.js? maybe Node? I'm experiencing the same thing, 404 when there isn't moduleID: module.id

**DashboardComponent**
```
@Component({
  //moduleId: module.id,
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',
})
```

**app.module**
```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import {DashboardComponent} from "./dashboard.component";
import { AppComponent }  from './app.component';
import { HeroDetailComponent } from './hero-details.component';
import { HeroesComponent } from './heroes.component';
import {HeroService} from "./hero.service";

@NgModule({
  imports:      [
    BrowserModule,
    FormsModule,
    RouterModule.forRoot([
      {
        path: 'dashboard',
        component: DashboardComponent
      },
      {
        path: '',
        redirectTo: '/dashboard',
        pathMatch: 'full'
      },
      {
        path: 'heroes',
        component: HeroesComponent
      }
    ])
  ],
  declarations: [
    DashboardComponent,
    AppComponent,
    HeroesComponent,
    HeroDetailComponent
  ],
  providers: [
    HeroService
  ],
  bootstrap:    [ AppComponent ]
})

export class AppModule { }
```

**Comment by ecarrera** [comment]
It is redundant having to specify the module id, doesn't it?

**Comment by ecarrera** [comment]
Also works when the path is: "../app/dashboard.component.html"... I really don't understand x'D

**Comment by Foxandxss** [comment]
I super lost track of this issue.

There is a loader (a plugin) of systemjs in all demos now that renders moduleId useless. So can leave it out and use relative paths `./foo.html`

**Comment by thomasvnl** [comment]
Also experiencing issue as specified by @ecarrera and @SamFarrington just now with the most recent git clone of the https://angular.io/docs/ts/latest/guide/setup.html Quickstart seed

**Comment by Foxandxss** [comment]
I need to bring the new loader into the quickstart seed. Sorry, buuuuuuuuuuusy week.

**Comment by thomasvnl** [comment]
@Foxandxss okay 👍

**Comment by sophistyx** [comment]
I've directed a few people to the TOH tutorial recently to get them started and they've all experienced the same issue so I thought I'd take a look and yes it's broken.   I haven't touched the tutorial for a long, long time and I have to say it's a total disgrace compared to how it once was.  Broken and confusing.  The standard of English in the tutorial is laughable, particularly in the Routing section.  I found myself having to read the same sentence over and over in order to makes sense of it, almost like all the words were there but in the wrong order.  I think you should rewrite the tutorial to use the CLI as that is without doubt the quickest and probably most likely entry point to Angular now.  Unimpressed.

**Comment by sophistyx** [comment]
I'd also like to question who's idea it was to take a very simple tutorial, one where you start with an empty folder and piece together a simple application, improving your knowledge as you go, and replace it with bringing down a seed project and then a set of instructions for deleting non-essential files?

**Comment by glederer** [comment]
@Foxandxss @Sir4ur0n I just want to be report as well I am facing exact same issue as @Sir4ur0n 👍  Adding "/app" prefix or adding   `moduleId: module.id` to the component  will make hmtl files load, but if none of these things are done (like in tutorial explanations, you get a 404 on html files.

**Comment by Foxandxss** [comment]
Do you have the `systemjs-angular-loader.js` file in `src/` ? It is needed (with a systemjs.config.js change).

**Comment by glederer** [comment]
Hey thanks for answering that fast. No I chekced and I don't, but I don't see this as a requirement in tutorial either right here (at least in the opage, but YES in the zip) : https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

**Comment by Foxandxss** [comment]
You are supposed to start the project using the quickstart repo and since it comes with that, it never says anything about it.

We need to update the docs to add a note saying that for quickstart users, you have that plugin in the quickstart and why.

I wrote a note for myself to make it clearer.

**Comment by glederer** [comment]
OK thank you very much, I realize the structure I have locally does not even have a `src` folder ... there has been weeks between the moment I started and now that I reach that 6th chapters with templateUrl, it seems things have changed... :)

**Comment by glederer** [comment]
@Foxandxss side note and my 2 cent suggestion : it would be nice to have, like some years ago in the angularjs tuto, a repo we could checkout at some tags representing the step you are currently learning. The 6th chapter is quiet long and I am now lost in the middle of it with an inconsitant code base that needs change but I do not see exactly where (I'll find my way out).
I realize this is yet some more work :) Awesome work and tutorial, thank you

**Comment by Foxandxss** [comment]
You can go and download the zips for each chapter.

**Comment by glederer** [comment]
Yes I can, indeed. What I meant is being able to checkout a repo at a specific stage/tag would be even more convinient.

**Comment by asantiago323** [comment]
It makes sense, like a before and after of each chapter, so you can
compare. They do it in a similar fashion at Team Treehouse.

**Comment by biblelogosthegame** [comment]
I agree with asantiago and glederer.  I assumed that it was my error since I didn't think that the official Angular Tutorial could have an issue like that.  I have had problems with the Thinkster Angular 2 tutorials because of the peer dependencies issues associated with breaking changes from the recent Angular CLI update.  I mention that because if anyone has any good Angular 2 tutorials that are always up to date with breaking changes, then I would appreciate it.  :)

**Comment by darincardin** [comment]
Is there any solution to this? From what I gather, if using templateUrl, you MUST include the absolute path. BUT, this will break when compiling with AOT, as the path must be relative. Thus, it is impossible to use templateUrl.
Also, using require() will not work either, as this will also break AOT. 

Is there anyone out there who has even gotten Angular 2 AOT to work properly?

**Comment by Yugloocamai** [comment]
@darincardin I've run into the same issue today. I think this is still an outstanding bug in Angular 2/4....  which really quite sad because it's so critical and blocking a lot of developers.

**Comment by Yugloocamai** [comment]
I worked around this problem by using a modified version of systemjs-angular-loader.js

changed line 42 from:
`
 urls.push('"' + basePath + match[2].substr(1) + '"');
`
to:
`
urls.push('"' + basePath.slice(1) + match[2].substr(1) + '"');
`
