### ISSUE TITLE
Angular2 Testing guide resource example not work : Error with external template

### ISSUE THREAD

**Issue by MrHOY** [angular/angular.io#3406]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I go to page: [https://angular.io/docs/ts/latest/guide/testing.html#!#live-examples](https://angular.io/docs/ts/latest/guide/testing.html#!#live-examples), and download a resource [A component spec with external template downloadable example](https://angular.io/resources/zips/testing/banner-specs.testing.zip)
Install package:  `npm install`
Run testing:  `npm test`

Image of error
![error](https://cloud.githubusercontent.com/assets/20653706/24185201/650a211e-0f04-11e7-9dce-f95cc9a2246a.jpg)

I see on plnkr it work good but i don't know why it have problem on my computer.

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **Browser:** [Chrome ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node:** `node --version` =   6.9.2
* **npm:**`npm --version` = 4.1.1

**Comment by Foxandxss** [comment]
I can reproduce it too.

Grrr. I will check as soon as I have time.

thanks for reporting it.

**Comment by apieceofbart** [comment]
Same here: https://github.com/angular/angular/issues/15513

**Comment by Foxandxss** [comment]
Should be fixed by now. If not leave a message.

**Comment by mrosso10** [comment]
@Foxandxss How can I test it?
I downloaded the live example from https://angular.io/resources/zips/testing/banner-specs.testing.zip and still get the same error.
Thanks
